# Generated by Django 3.1 on 2020-08-24 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybooth', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mybooth.category'),
        ),
        migrations.AddField(
            model_name='image',
            name='locatoin',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mybooth.locatoin'),
        ),
    ]
